Update 2z_channel_logger.yml

diff --git a/.github/workflows/2z_channel_logger.yml b/.github/workflows/2z_channel_logger.yml
--- a/.github/workflows/2z_channel_logger.yml
+++ b/.github/workflows/2z_channel_logger.yml
@@ -24,33 +24,24 @@ jobs:
       - name: Open and Process File
         run: |
           while read -r line; do
+            # Check if ", " exists in the line
+            if [[ ! $line =~ ", " ]]; then
+                echo "Error: \", \" not found in the line. Exiting script."
+                exit 1
+            fi
+
             # Remove "New: " from the line
             channel_info=$(echo "$line" | sed 's/New: //')
-  
+
             # Extract channel_name by finding the first ", " and removing everything after it
             channel_name=$(echo "$channel_info" | awk -F ', ' '{print $1}')
 
-            # Debugging output
-            echo "Processing line: $line"
-            echo "Extracted channel_name: $channel_name"
-  
-            # Check if the file is empty
-            if [ ! -s current_channels.txt ]; then
-                echo "File is empty. Adding $channel_name to youtube_channel_info.txt"
+            # Check if the channel_name exists in current_channels.txt
+            if ! grep -q "$channel_name" current_channels.txt; then
+                echo "$channel_name not found. Adding $channel_name to youtube_channel_info.txt"
                 echo "$line" >> youtube_channel_info.txt
-            elif grep -q "$channel_name" current_channels.txt; then
-                echo "$channel_name has been added, transferred to log"
-  
-                # Copy line to recently_added_channels.txt
-                echo "$line" >> recently_added_channels.txt
-  
-                # Remove line from youtube_channel_info.txt
-                awk -v pattern="$line" '$0 != pattern' youtube_channel_info.txt > tmpfile && mv tmpfile youtube_channel_info.txt
             else
-                echo "Searched for $channel_name, match not found."
-  
-                # Restore the original line to youtube_channel_info.txt
-                echo "$line" >> youtube_channel_info.txt
+                echo "$channel_name already exists. Disregarding."
             fi
           done < youtube_channel_info.txt
 
