Update d_fetch_vod.yml

diff --git a/.github/workflows/d_fetch_vod.yml b/.github/workflows/d_fetch_vod.yml
--- a/.github/workflows/d_fetch_vod.yml
+++ b/.github/workflows/d_fetch_vod.yml
@@ -43,25 +43,27 @@ jobs:
 
           start_time=$(date +%s)
           attempts=0
+          broken_pipe_count=0
           fallback_url_attempt=0
           
           while [ $attempts -lt 3 ]; do
             echo "Attempting to extract video URL (Attempt $((attempts + 1)))..."
-            m3u8_url=$(yt-dlp "$modified_url" --get-url --skip-download)
+            m3u8_url=$(timeout 10 yt-dlp "$modified_url" --get-url --skip-download 2>/dev/null)
             
             if [ $? -eq 0 ]; then
               echo "Video URL found: $m3u8_url"
               echo $m3u8_url >> "$m3u8_file"
               break
-            else
-              if [ $fallback_url_attempt -eq 0 ]; then
-                echo "First attempt failed. Trying with fallback URL..."
-                modified_url="${live_url/live/}"
-                fallback_url_attempt=$((fallback_url_attempt + 1))
-              else
-                echo "Error extracting video URL. Attempt $((attempts + 1)) failed."
+            elif [ $? -eq 32 ]; then
+              echo "Error: Broken pipe"
+              ((broken_pipe_count++))
+              if [ $broken_pipe_count -eq 2 ]; then
+                echo "Two broken pipe errors occurred. Moving on to the next entry."
                 break
               fi
+            else
+              echo "Error extracting video URL. Attempt $((attempts + 1)) failed."
+              break
             fi
             
             ((attempts++))
@@ -82,11 +84,11 @@ jobs:
           done < "$m3u8_file"
 
           mv "./vod/$channel_name/vod_videos_temp.m3u8" "$m3u8_file"
+        done
 
-          echo "Committing changes..."
-          git config --global user.email "you@example.com"
-          git config --global user.name "Your Name"
-          git add -A
-          git diff --cached --quiet || git commit -m "Updated M3U8 files"
-          git push origin main
-        done < ./program/alt_urls.txt
+        echo "Committing changes..."
+        git config --global user.email "you@example.com"
+        git config --global user.name "Your Name"
+        git add -A
+        git diff --cached --quiet || git commit -m "Updated M3U8 files"
+        git push origin main
