Update d_fetch_vod.yml

diff --git a/.github/workflows/d_fetch_vod.yml b/.github/workflows/d_fetch_vod.yml
--- a/.github/workflows/d_fetch_vod.yml
+++ b/.github/workflows/d_fetch_vod.yml
@@ -35,58 +35,30 @@ jobs:
           
           echo "Modified URL: $modified_url"
 
-          mkdir -p "./vod/$channel_name"
+          mkdir -p ./vod/$channel_name
           m3u8_file="./vod/$channel_name/vod_videos.m3u8"
 
           # Truncate the file before writing
           : > "$m3u8_file"
 
           start_time=$(date +%s)
-          attempts=0
-          fallback_url_attempt=0
-          broken_pipe_count=0
-          
-          while [ $attempts -lt 3 ]; do
-            echo "Attempting to extract video URL (Attempt $((attempts + 1)))..."
-            
-            # Use --simulate to check if the video is live or scheduled
-            is_live_or_scheduled=$(yt-dlp "$modified_url" --simulate | grep "This live event will begin\|This video will be published\|This video is scheduled")
-            
-            if [ -n "$is_live_or_scheduled" ]; then
-              echo "Found live or scheduled video. Skipping..."
-              break
-            fi
-            
-            m3u8_url=$(timeout 10 yt-dlp "$modified_url" --get-url --skip-download --format "bestvideo[ext=m3u8]+bestaudio[ext=m4a]/best[ext=m3u8]/best" || true)  # Ignore errors
-            
-            if [ $? -eq 0 ]; then
-              # Check if the URL is an M3U8 link
-              if [[ $m3u8_url == *".m3u8"* ]]; then
-                echo "M3U8 Video URL found: $m3u8_url"
-                echo "$m3u8_url" >> "$m3u8_file"
-                break
-              else
-                echo "Found non-M3U8 link. Skipping..."
-              fi
+          for i in {1..2}; do
+            echo "Attempting to extract video URL (Attempt $i)..."
+            m3u8_url=$(timeout 30 yt-dlp "$modified_url" --get-url --skip-download 2>&1)
+            if [ $? -eq 0 ] && [ -n "$m3u8_url" ]; then
+              echo "Video URL found: $m3u8_url"
+              echo $m3u8_url >> "$m3u8_file"
+              break  # Break out of the loop if a URL is found
             else
-              if [[ "$m3u8_url" == *"broken pipe"* ]]; then
-                echo "Encountered 'broken pipe' response. Retrying..."
-                ((broken_pipe_count++))
-                if [ $broken_pipe_count -ge 2 ]; then
-                  echo "Received 'broken pipe' response twice. Moving on to the next entry."
-                  break
-                fi
-              else
-                echo "Error extracting video URL. Attempt $((attempts + 1)) failed. Error: $m3u8_url"
-              fi
+              echo "Error extracting video URL. Retrying..."
+              # For the second attempt, retry with the modified URL without "/live" or "/streams"
+              modified_url="${live_url/live/}"
             fi
-            
-            ((attempts++))
-            sleep 2  # Sleep for 2 seconds between attempts
           done
 
-          if [ $broken_pipe_count -ge 2 ]; then
-            continue  # Skip to the next entry in case of two 'broken pipe' responses
+          if [ ! -s "$m3u8_file" ]; then
+            echo "No video URL found. Moving on to the next channel."
+            continue
           fi
 
           echo "M3U8 content:"
@@ -110,4 +82,4 @@ jobs:
           git add -A
           git diff --cached --quiet || git commit -m "Updated M3U8 files"
           git push origin main
-        done < ./program/alt_urls.txt
+        done < ./program/alt_url.txt
