Update d_fetch_vod.yml

diff --git a/.github/workflows/d_fetch_vod.yml b/.github/workflows/d_fetch_vod.yml
--- a/.github/workflows/d_fetch_vod.yml
+++ b/.github/workflows/d_fetch_vod.yml
@@ -42,17 +42,24 @@ jobs:
           : > "$m3u8_file"
 
           start_time=$(date +%s)
-          for i in {1..3}; do
+          for i in {1..2}; do
             echo "Attempting to extract video URL (Attempt $i)..."
             m3u8_url=$(timeout 30 yt-dlp "$modified_url" --get-url --skip-download)
-            if [ $? -eq 0 ]; then
+            if [ $? -eq 0 ] && [ -n "$m3u8_url" ]; then
               echo "Video URL found: $m3u8_url"
               echo $m3u8_url >> "$m3u8_file"
+              break  # Break out of the loop if a URL is found
             else
-              echo "Error extracting video URL. Skipping to the next."
-              break
+              echo "Error extracting video URL. Retrying..."
+              # For the second attempt, remove "/streams" from the URL
+              modified_url="${live_url/live/}"
             fi
           done
+
+          if [ ! -s "$m3u8_file" ]; then
+            echo "No video URL found. Moving on to the next channel."
+            continue
+          fi
 
           echo "M3U8 content:"
           cat "$m3u8_file"
