Update d_fetch_vod.yml

diff --git a/.github/workflows/d_fetch_vod.yml b/.github/workflows/d_fetch_vod.yml
--- a/.github/workflows/d_fetch_vod.yml
+++ b/.github/workflows/d_fetch_vod.yml
@@ -25,63 +25,47 @@ jobs:
         git pull origin main --no-edit
         git rebase origin/main
 
-    - name: Read search term from file
-      id: read-search-term
+    - name: Read search terms from file
       run: |
-        content=$(cat ./program/alt_urls.txt)
-        search_term=$(echo "$content" | cut -d ',' -f 1 | awk -F', ' '{print $1}')
-        echo "::set-output name=search_term::$search_term"
+        IFS=',' read -ra search_terms <<< $(cat ./program/alt_urls.txt)
+        for term in "${search_terms[@]}"; do
+          echo "Processing search term: $term"
+          
+          mkdir -p ./vod/$term
+          touch ./vod/$term/vod_videos.m3u8
 
-    - name: Print extracted search term
-      run: |
-        echo "Extracted Search Term: ${{ steps.read-search-term.outputs.search_term }}"
-        echo "SEARCH_TERM=${{ steps.read-search-term.outputs.search_term }}" >> $GITHUB_ENV
+          start_time=$(date +%s)
+          for i in {1..3}; do
+            echo "Attempting to extract video URL (Attempt $i)..."
+            m3u8_url=$(timeout 5 yt-dlp "ytsearch:${term}" --get-url --skip-download)
+            if [ $? -eq 0 ]; then
+              echo "Video URL found: $m3u8_url"
+              echo $m3u8_url >> ./vod/$term/vod_videos.m3u8
+            else
+              echo "Error extracting video URL. Skipping to the next."
+              break
+            fi
+          done
 
-    - name: Extract top 3 video URLs
-      run: |
-        search_term=${{ steps.read-search-term.outputs.search_term }}
-        # Create directory if it doesn't exist
-        mkdir -p ./vod/$search_term
-        # Touch the file to ensure it exists
-        touch ./vod/$search_term/vod_videos.m3u8
-        start_time=$(date +%s)
-        for i in {1..3}; do
-          echo "Attempting to extract video URL (Attempt $i)..."
-          m3u8_url=$(timeout 5 yt-dlp "ytsearch:${search_term}" --get-url --skip-download)
-          if [ $? -eq 0 ]; then
-            echo "Video URL found: $m3u8_url"
-            echo $m3u8_url >> ./vod/$search_term/vod_videos.m3u8
-          else
-            echo "Error extracting video URL. Skipping to the next."
-            break
-          fi
+          echo "M3U8 content:"
+          cat ./vod/$term/vod_videos.m3u8
+
+          echo "Creating M3U8 file..."
+          echo "#EXTM3U" > ./vod/$term/vod_videos_temp.m3u8
+          echo "#EXT-X-VERSION:3" >> ./vod/$term/vod_videos_temp.m3u8
+          video_number=1
+          while read -r line; do
+            echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=${video_number}" >> ./vod/$term/vod_videos_temp.m3u8
+            echo "${line}" >> ./vod/$term/vod_videos_temp.m3u8
+            ((video_number++))
+          done < ./vod/$term/vod_videos.m3u8
+
+          mv ./vod/$term/vod_videos_temp.m3u8 ./vod/$term/vod_videos.m3u8
+
+          echo "Committing changes..."
+          git config --global user.email "you@example.com"
+          git config --global user.name "Your Name"
+          git add -A
+          git diff --cached --quiet || git commit -m "Updated M3U8 files"
+          git push origin main
         done
-
-    - name: Print M3U8 content
-      run: |
-        echo "M3U8 content:"
-        cat ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
-
-    - name: Create M3U8 file
-      run: |
-        echo "#EXTM3U" > ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos_temp.m3u8
-        echo "#EXT-X-VERSION:3" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos_temp.m3u8
-        video_number=1
-        while read -r line; do
-          echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=${video_number}" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos_temp.m3u8
-          echo "${line}" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos_temp.m3u8
-          ((video_number++))
-        done < ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
-
-        mv ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos_temp.m3u8 ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
-
-    - name: Configure Git
-      run: |
-        git config --global user.email "you@example.com"
-        git config --global user.name "Your Name"
-
-    - name: Commit changes
-      run: |
-        git add -A
-        git diff --cached --quiet || git commit -m "Updated M3U8 files"
-        git push origin main
