Update metadata.yml

diff --git a/.github/workflows/metadata.yml b/.github/workflows/metadata.yml
--- a/.github/workflows/metadata.yml
+++ b/.github/workflows/metadata.yml
@@ -26,26 +26,18 @@ jobs:
     - name: Run scrape script
       run: |
         echo "Running metadata.py"
-        python metadata.py > output.txt 2>&1
-
-        # Print the contents of output.txt for debugging
+        python metadata.py > output.txt 2>&1 || echo "Script failed with exit code $?"
         echo "Script Output:"
         cat output.txt
-
-        # Print metadata dump for debugging
         echo "Metadata Dump:"
         cat meta_dump.txt
-
       continue-on-error: true
-
-    - name: Check Git Status
-      run: git status
-
-    - name: Print XML Contents
-      run: cat combined_epg.xml
 
     - name: Remove untracked files
       run: git clean -fdX
+
+    - name: Print XML Contents
+      run: cat combined_epg.xml
 
     - name: Commit and push changes
       run: |
